version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app
    container_name: apicrm_nginx

  app:
    build:
      args:
          user: amoapi
          uid: 1000
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    container_name: apicrm_php
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: apicrm_db
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: apicrm_db